//! JSON interop — the machine-readable twin of the canonical TOML.
//!
//! # Why TOML is canonical, and JSON is not
//!
//! **Because TOML carries COMMENTS and JSON cannot.** ksx config files are
//! annotated: `mouse_move_deadzone = 5  # 0..12`, the reason a cabinet's
//! `launcher_grace_ms` was raised to 20 s, which panel a `[[device]]` id
//! belongs to. Those notes are the difference between a file a human can
//! maintain a year later and a blob nobody dares touch — and they are the same
//! difference for an AI reading the file, which gets the *intent* alongside the
//! value instead of having to infer it. JSON has no syntax for any of that, so
//! a JSON-canonical ksx would have to throw the annotations away on every
//! write. That decided it; nothing else came close.
//!
//! Two smaller reasons point the same way: TOML is what every existing KSX
//! file, snapshot and doc already is, and TOML's `[[slot]]`/dotted-key shapes
//! read better by hand than the equivalent nesting.
//!
//! # Why JSON exists anyway
//!
//! For the readers that are not people:
//!
//! - **preset sharing (M7)** — one file, one preset, no ambiguity about
//!   whitespace or comment style, trivially posted through anything;
//! - **AI-generated configs (E5, `docs/ENHANCEMENTS.md`)** — an assistant asked
//!   to wire a cabinet emits JSON reliably; the AI-drivable CLI is the point;
//! - **anything that wants a schema** — a JSON document can be validated,
//!   diffed and generated by tooling that has never heard of TOML.
//!
//! # Why drift is impossible by construction
//!
//! Both formats go through the **same serde types** — [`ConfigFile`],
//! [`GamesFile`], [`PresetFile`]. There is no second schema, no parallel
//! struct, no hand-written JSON writer. A field added to a config type is in
//! both formats the moment it compiles, which is also why the newer shapes
//! (personas, SOCD, chords with `when`/`unless`, multi-key list bindings) need
//! no interop code of their own. That is not a claim, it is a demonstrated
//! one: `[macros.<name>]` landed in [`PresetFile`] while this module was being
//! written and cost the interop layer exactly zero lines — the round-trip
//! tests below picked it up by construction.
//!
//! # Precedence when both exist
//!
//! `config.toml` and `config.json` side by side (or `presets/Foo.toml` and
//! `presets/Foo.json`): **the TOML wins and the JSON is ignored**, with a
//! [`crate::WarningKind::ShadowedByCanonicalToml`] naming the ignored file.
//! They are never merged. A merge would need a rule for every conflicting
//! field, and the first time it guessed wrong it would guess wrong silently —
//! on a file the user believed was authoritative. One winner, said out loud.
//!
//! # The one thing JSON does not get
//!
//! Schema **migration**. [`crate::Store`]'s migration steps operate on a raw
//! `toml::Table`, because the canonical file is the one that has to survive
//! upgrades. A `.json` config whose `schema_version` is not this build's is
//! refused rather than migrated: convert it to TOML, let ksx migrate that, and
//! export JSON again. (Today's registry is empty — v1 is the first schema — so
//! this costs nothing yet; it is written down so it cannot surprise anyone
//! later.)

use std::fmt;
use std::path::Path;

use serde::de::DeserializeOwned;
use serde::{Deserialize, Serialize};

use crate::config::{ConfigFile, SCHEMA_VERSION};
use crate::error::ConfigError;
use crate::games::GamesFile;
use crate::preset::PresetFile;
use crate::store::{Loaded, Warning, WarningKind};

/// Version of the interop ENVELOPE (not of the config schema — that is
/// [`SCHEMA_VERSION`], and it travels in the same document).
///
/// Bumped only when the envelope's own shape changes. A reader refuses a
/// document from the future rather than half-understanding it.
pub const INTEROP_VERSION: u32 = 1;

/// On-disk spelling of a config file.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Format {
    /// Canonical: comments survive, migrations run here.
    Toml,
    /// Interop: machine-generated, machine-read.
    Json,
}

impl Format {
    /// The format a path's extension names, or `None` for anything else.
    pub fn of(path: &Path) -> Option<Self> {
        let ext = path.extension()?.to_str()?;
        if ext.eq_ignore_ascii_case("toml") {
            Some(Self::Toml)
        } else if ext.eq_ignore_ascii_case("json") {
            Some(Self::Json)
        } else {
            None
        }
    }

    /// Extension WITHOUT the dot.
    pub fn extension(self) -> &'static str {
        match self {
            Self::Toml => "toml",
            Self::Json => "json",
        }
    }
}

impl fmt::Display for Format {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.extension())
    }
}

/// Indentation policy for a rendered document.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum JsonStyle {
    /// Indented and newline-separated — diffable, reviewable, the default.
    #[default]
    Pretty,
    /// One line, no spare whitespace — for pipes and transports.
    Compact,
}

/// One of the three things a ksx config root holds.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Part {
    Config,
    Games,
    Presets,
}

impl Part {
    pub const ALL: [Part; 3] = [Part::Config, Part::Games, Part::Presets];

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Config => "config",
            Self::Games => "games",
            Self::Presets => "presets",
        }
    }

    /// The CLI spelling (`--what config|games|presets`).
    pub fn parse(s: &str) -> Option<Self> {
        match s.trim().to_ascii_lowercase().as_str() {
            "config" => Some(Self::Config),
            "games" => Some(Self::Games),
            "presets" | "preset" => Some(Self::Presets),
            _ => None,
        }
    }
}

impl fmt::Display for Part {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

/// The interop document: an envelope plus whichever parts it carries.
///
/// Every field is optional, so `--what config` and `--what all` produce the
/// same shape with different fields filled in — one parser on the way back.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Bundle {
    /// [`INTEROP_VERSION`] — also the marker that makes a document
    /// self-describing (see [`parse_document`]).
    pub ksx_interop: u32,
    /// The config schema these documents belong to ([`SCHEMA_VERSION`]).
    pub schema_version: u32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<ConfigFile>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub games: Option<GamesFile>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub presets: Option<Vec<PresetFile>>,
}

impl Default for Bundle {
    fn default() -> Self {
        Self {
            ksx_interop: INTEROP_VERSION,
            schema_version: SCHEMA_VERSION,
            config: None,
            games: None,
            presets: None,
        }
    }
}

impl Bundle {
    /// Which parts this document actually carries, in a stable order.
    pub fn parts(&self) -> Vec<Part> {
        Part::ALL
            .into_iter()
            .filter(|part| self.has(*part))
            .collect()
    }

    pub fn has(&self, part: Part) -> bool {
        match part {
            Part::Config => self.config.is_some(),
            Part::Games => self.games.is_some(),
            Part::Presets => self.presets.is_some(),
        }
    }

    pub fn is_empty(&self) -> bool {
        self.parts().is_empty()
    }

    /// Drop everything not in `keep`. Used by `--what` on the import side, so
    /// a full backup can be replayed one part at a time.
    pub fn narrow(&mut self, keep: &[Part]) {
        for part in Part::ALL {
            if keep.contains(&part) {
                continue;
            }
            match part {
                Part::Config => self.config = None,
                Part::Games => self.games = None,
                Part::Presets => self.presets = None,
            }
        }
    }

    /// Render. `Pretty` is the default because an exported config is read by
    /// people at least as often as by programs.
    pub fn to_json(&self, style: JsonStyle) -> Result<String, ConfigError> {
        let rendered = match style {
            JsonStyle::Pretty => serde_json::to_string_pretty(self),
            JsonStyle::Compact => serde_json::to_string(self),
        };
        rendered.map_err(|e| ConfigError::JsonRender {
            message: e.to_string(),
        })
    }
}

/// Typed JSON parse that records ignored keys as [`Warning`]s instead of
/// failing — the JSON twin of the store's lenient TOML parse, and lenient for
/// the same reason: a document written by a newer ksx (or by an assistant that
/// guessed one extra field) must degrade to a warning, never to a refusal.
pub fn parse_lenient<T: DeserializeOwned>(
    path: &Path,
    content: &str,
) -> Result<Loaded<T>, ConfigError> {
    let value: serde_json::Value =
        serde_json::from_str(content).map_err(|e| ConfigError::Parse {
            path: path.to_owned(),
            message: e.to_string(),
        })?;
    from_value_lenient(path, value)
}

fn from_value_lenient<T: DeserializeOwned>(
    path: &Path,
    value: serde_json::Value,
) -> Result<Loaded<T>, ConfigError> {
    let mut warnings = Vec::new();
    let parsed = serde_ignored::deserialize(value, |ignored| {
        warnings.push(Warning {
            file: path.to_owned(),
            kind: WarningKind::UnknownKey {
                path: ignored.to_string(),
            },
        });
    })
    .map_err(|e: serde_json::Error| ConfigError::Parse {
        path: path.to_owned(),
        message: e.to_string(),
    })?;
    Ok(Loaded {
        value: parsed,
        warnings,
    })
}

/// Render any config type as JSON. The same value the TOML writer would take,
/// so the two formats cannot disagree about what a type contains.
pub fn to_json<T: Serialize>(value: &T, style: JsonStyle) -> Result<String, ConfigError> {
    let rendered = match style {
        JsonStyle::Pretty => serde_json::to_string_pretty(value),
        JsonStyle::Compact => serde_json::to_string(value),
    };
    rendered.map_err(|e| ConfigError::JsonRender {
        message: e.to_string(),
    })
}

/// Parse an interop document.
///
/// Two shapes are accepted, and which one it is, is DETECTED rather than
/// guessed:
///
/// - **enveloped** — a top-level object carrying `ksx_interop`. It describes
///   itself; `bare` is ignored.
/// - **bare** — a single [`ConfigFile`], [`GamesFile`], [`PresetFile`], or an
///   array of presets. This is what a hand-written or AI-generated file
///   usually looks like, so it is supported — but the type it is cannot be
///   sniffed reliably (a `PresetFile` and a `GamesFile` are both just objects),
///   so `bare` must name it. Without it the document is refused with
///   [`ConfigError::UntaggedJson`] rather than guessed: importing the wrong
///   file over the wrong file is exactly the failure this crate exists to
///   prevent.
pub fn parse_document(
    path: &Path,
    content: &str,
    bare: Option<Part>,
) -> Result<Loaded<Bundle>, ConfigError> {
    let value: serde_json::Value =
        serde_json::from_str(content).map_err(|e| ConfigError::Parse {
            path: path.to_owned(),
            message: e.to_string(),
        })?;

    let enveloped = value
        .as_object()
        .is_some_and(|obj| obj.contains_key("ksx_interop"));
    if enveloped {
        let found = value
            .get("ksx_interop")
            .and_then(serde_json::Value::as_u64)
            .unwrap_or(u64::from(u32::MAX));
        if found > u64::from(INTEROP_VERSION) {
            return Err(ConfigError::UnsupportedInteropVersion {
                path: path.to_owned(),
                found,
                supported: INTEROP_VERSION,
            });
        }
        return from_value_lenient(path, value);
    }

    let Some(part) = bare else {
        return Err(ConfigError::UntaggedJson {
            path: path.to_owned(),
        });
    };
    let mut bundle = Bundle::default();
    let warnings;
    match part {
        Part::Config => {
            let loaded: Loaded<ConfigFile> = from_value_lenient(path, value)?;
            bundle.schema_version = loaded.value.schema_version;
            bundle.config = Some(loaded.value);
            warnings = loaded.warnings;
        }
        Part::Games => {
            let loaded: Loaded<GamesFile> = from_value_lenient(path, value)?;
            bundle.games = Some(loaded.value);
            warnings = loaded.warnings;
        }
        // One preset or a list of them: sharing a single preset is the common
        // case, and a list is what "share my whole panel" wants.
        Part::Presets => {
            if value.is_array() {
                let loaded: Loaded<Vec<PresetFile>> = from_value_lenient(path, value)?;
                bundle.presets = Some(loaded.value);
                warnings = loaded.warnings;
            } else {
                let loaded: Loaded<PresetFile> = from_value_lenient(path, value)?;
                bundle.presets = Some(vec![loaded.value]);
                warnings = loaded.warnings;
            }
        }
    }
    Ok(Loaded {
        value: bundle,
        warnings,
    })
}

/// The schema gate for a `.json` config file.
///
/// The typed parse would fail on a missing `schema_version` anyway; this runs
/// first so the error is the same structured one the TOML path produces, and
/// so an old-schema JSON is refused with the migration advice rather than with
/// a field-by-field type error. See the module docs: JSON is not the migration
/// substrate.
pub fn json_schema_gate(path: &Path, content: &str) -> Result<(), ConfigError> {
    let value: serde_json::Value =
        serde_json::from_str(content).map_err(|e| ConfigError::Parse {
            path: path.to_owned(),
            message: e.to_string(),
        })?;
    let found = match value
        .get("schema_version")
        .and_then(serde_json::Value::as_i64)
    {
        Some(found) => found,
        None => {
            return Err(ConfigError::MissingSchemaVersion {
                path: path.to_owned(),
            })
        }
    };
    if found == i64::from(SCHEMA_VERSION) {
        return Ok(());
    }
    Err(ConfigError::UnsupportedSchemaVersion {
        path: path.to_owned(),
        found,
        supported: SCHEMA_VERSION,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Backend, DeviceEntry, Settings, SlotEntry};
    use crate::games::{GameEntry, GameSlotEntry};
    use crate::preset::{BindingEntry, GuardedEntry, MacroFile, MacroStepFile};
    use ksx_core::{
        Axis, Binding, Blocking, Chord, DpadDirection, Key, Persona, Preset, Socd, AXIS_MIN,
    };
    use std::path::PathBuf;

    fn p() -> PathBuf {
        PathBuf::from("<test>")
    }

    // ---- fixtures: every shape the file types can take ---------------------

    /// A config exercising personas, SOCD, both backends, aliases and literal
    /// instance paths. Anything a `[[slot]]` can hold is in here.
    fn rich_config() -> ConfigFile {
        ConfigFile {
            schema_version: SCHEMA_VERSION,
            settings: Settings {
                block_keyboards: Blocking::Off,
                block_mice: true,
                mouse_move_deadzone: 11,
                starting_user_index: 3,
                theme: Some("light".to_owned()),
                board: None,
            },
            devices: vec![
                DeviceEntry {
                    id: r"HID\VID_D209&PID_0430&MI_00\8&A1B2C3D4&0&0000"
                        .parse()
                        .unwrap(),
                    alias: "P1 I-PAC".into(),
                    backend: Backend::Interception,
                },
                DeviceEntry {
                    id: r"USB\VID_D209&PID_0430&MI_01\7&1".parse().unwrap(),
                    alias: "P2 I-PAC".into(),
                    backend: Backend::Winusb,
                },
            ],
            slots: vec![
                SlotEntry {
                    number: 1,
                    keyboard: Some("P1 I-PAC".into()),
                    mouse: None,
                    preset: "Panel P1".into(),
                    persona: Persona::Xbox360,
                    socd: Socd::default(),
                    macros: Default::default(),
                    sources: Vec::new(),
                },
                SlotEntry {
                    number: 5,
                    keyboard: Some(r"HID\VID_AAAA&PID_BBBB\1&2&3".into()),
                    mouse: Some("P2 I-PAC".into()),
                    preset: "Panel P2".into(),
                    persona: Persona::PlayStation,
                    socd: Socd::Neutral,
                    macros: ksx_core::MacroSwitch::Off,
                    sources: Vec::new(),
                },
            ],
        }
    }

    fn rich_games() -> GamesFile {
        GamesFile {
            games: vec![
                GameEntry {
                    title: "Example Launcher".into(),
                    notes: "the launcher that taught us launcher_grace_ms".into(),
                    path: r"C:\Examples\example-launcher.exe".into(),
                    arguments: "-silent".into(),
                    process_name: Some("portal2.exe".into()),
                    launcher_grace_ms: Some(20_000),
                    // The third state, in the fixture that exists to make every
                    // shape cross JSON: a bool cannot carry it.
                    block_keyboards: Blocking::BoundKeys,
                    block_mice: false,
                    slots: vec![GameSlotEntry {
                        number: 1,
                        user_index: Some(1),
                        keyboard: Some(r"HID\VID_D209&PID_0430&REV_0001&MI_00".into()),
                        mouse: None,
                        preset: "Panel P1".into(),
                        persona: Persona::PlayStation,
                        socd: Socd::UpPriority,
                        macros: ksx_core::MacroSwitch::Off,
                        sources: Vec::new(),
                    }],
                },
                // The minimal shape: every optional field absent.
                GameEntry {
                    title: "MAME".into(),
                    notes: String::new(),
                    path: r"C:\mame\mame.exe".into(),
                    arguments: String::new(),
                    process_name: None,
                    launcher_grace_ms: None,
                    block_keyboards: Blocking::Off,
                    block_mice: true,
                    slots: Vec::new(),
                },
            ],
        }
    }

    /// Every [`BindingEntry`] variant at once: one key, a multi-key list, a
    /// chord with `when` AND `unless`, a mixed plain+guarded list, a nested
    /// dotted group, and a consume-only guard.
    fn rich_preset() -> PresetFile {
        let mut bindings = std::collections::BTreeMap::new();
        bindings.insert("A".to_owned(), BindingEntry::Key("S".into()));
        bindings.insert(
            "B".to_owned(),
            BindingEntry::Keys(vec!["D".into(), "Enter".into(), "Space".into()]),
        );
        bindings.insert(
            "rt".to_owned(),
            BindingEntry::Guarded(GuardedEntry {
                key: "A".into(),
                when: vec!["B".into(), "C".into()],
                unless: vec!["LeftShift".into()],
                turbo_hz: None,
                toggle: None,
            }),
        );
        bindings.insert(
            "lb".to_owned(),
            BindingEntry::Many(vec![
                BindingEntry::Key("Q".into()),
                BindingEntry::Key("E".into()),
                BindingEntry::Guarded(GuardedEntry {
                    key: "A".into(),
                    when: vec!["C".into()],
                    unless: Vec::new(),
                    turbo_hz: None,
                    toggle: None,
                }),
            ]),
        );
        bindings.insert("dpad.up".to_owned(), BindingEntry::Key("I".into()));
        bindings.insert("macro.hadouken".to_owned(), BindingEntry::Key("P".into()));
        bindings.insert("lx.min".to_owned(), BindingEntry::Key("Left".into()));
        bindings.insert("lx.-16384".to_owned(), BindingEntry::Key("None".into()));
        bindings.insert(
            "consume".to_owned(),
            BindingEntry::Guarded(GuardedEntry {
                key: "Left".into(),
                when: vec!["Right".into()],
                unless: Vec::new(),
                turbo_hz: None,
                toggle: None,
            }),
        );
        // Built by MUTATING a real instance rather than with a struct literal:
        // when `PresetFile` grows a field, the fixture carries it at its
        // default instead of failing to compile, and the round-trip below
        // covers the new field for free. (That is exactly how MACROS arrived:
        // the interop layer needed no change at all.)
        let mut file = PresetFile::from_core(&Preset::builtin_empty());
        file.name = "Panel P1".into();
        file.bindings = bindings;
        file.macros = rich_macros();
        file
    }

    /// A macro with every knob off its default: both timing units (`ms` and
    /// `frames`), a neutral gap, a flagged short step, and all three policy
    /// enums away from their defaults.
    ///
    /// Written as an explicit struct literal on purpose — a new field on
    /// `MacroFile`/`MacroStepFile` should break THIS line, so somebody decides
    /// whether the round-trip covers it, rather than defaulting past it.
    fn rich_macros() -> std::collections::BTreeMap<String, MacroFile> {
        let step = |hold: &[&str], ms: Option<u32>, frames: Option<u32>, allow_short: bool| {
            MacroStepFile {
                hold: hold.iter().map(|name| (*name).to_owned()).collect(),
                ms,
                frames,
                allow_short,
            }
        };
        [(
            "hadouken".to_owned(),
            MacroFile {
                steps: vec![
                    step(&["dpad.down"], Some(50), None, false),
                    // The other timing unit, on the same macro.
                    step(&["dpad.down", "dpad.right"], None, Some(3), false),
                    // A deliberate neutral gap, deliberately short.
                    step(&[], Some(4), None, true),
                    step(&["A"], Some(50), None, false),
                ],
                on_release: ksx_core::macros::OnRelease::Abort,
                retrigger: ksx_core::macros::Retrigger::Restart,
                interrupt: ksx_core::macros::Interrupt::Opposing,
                repeat: ksx_core::macros::Repeat::Turbo,
                // The rate, in the unit it was authored in — `gap_ms` is the
                // other spelling and the round-trip must not swap them.
                turbo_hz: Some(12),
                gap_ms: None,
                // Away from its default too — `enabled = false` must survive
                // every export/import path, or a disabled macro comes back on.
                enabled: false,
            },
        )]
        .into_iter()
        .collect()
    }

    /// [`rich_preset`] plus a NESTED dotted group (`dpad = { up = … }`), the
    /// one `BindingEntry` shape the TOML writer never emits — it only ever
    /// arrives by parsing — so it is exercised on the JSON side only.
    fn preset_with_nested_group() -> PresetFile {
        let mut file = rich_preset();
        file.bindings.insert(
            "dpad".to_owned(),
            BindingEntry::Group(
                [
                    ("left".to_owned(), BindingEntry::Key("J".into())),
                    (
                        "down".to_owned(),
                        BindingEntry::Keys(vec!["K".into(), "Down".into()]),
                    ),
                ]
                .into_iter()
                .collect(),
            ),
        );
        file
    }

    // ---- the round-trip guarantee -----------------------------------------

    /// TOML → JSON → TOML, generic over the type, so a NEW config type (or a
    /// new field on an existing one — macros, when they land) is covered by
    /// adding it to the fixture list and nothing else.
    fn round_trip<T>(original: &T)
    where
        T: Serialize + DeserializeOwned + PartialEq + fmt::Debug,
    {
        // The canonical hop, exactly as the store writes it.
        let toml_text = toml::to_string(original).expect("toml render");
        let from_toml: T = toml::from_str(&toml_text).expect("toml parse");
        assert_eq!(&from_toml, original, "TOML did not round-trip\n{toml_text}");

        // ...out to JSON, in both styles...
        for style in [JsonStyle::Pretty, JsonStyle::Compact] {
            let json_text = to_json(&from_toml, style).expect("json render");
            let loaded: Loaded<T> = parse_lenient(&p(), &json_text).expect("json parse");
            assert!(
                loaded.warnings.is_empty(),
                "JSON round-trip warned: {:?}\n{json_text}",
                loaded.warnings
            );
            assert_eq!(
                &loaded.value, original,
                "JSON did not round-trip\n{json_text}"
            );

            // ...and back to canonical TOML, byte-for-byte the same file.
            let back = toml::to_string(&loaded.value).expect("toml re-render");
            assert_eq!(
                back, toml_text,
                "TOML→JSON→TOML changed the file\n{json_text}"
            );
        }
    }

    #[test]
    fn config_round_trips_toml_to_json_to_toml() {
        round_trip(&rich_config());
        round_trip(&ConfigFile::default());
    }

    #[test]
    fn games_round_trip_toml_to_json_to_toml() {
        round_trip(&rich_games());
        round_trip(&GamesFile::default());
    }

    #[test]
    fn presets_round_trip_toml_to_json_to_toml() {
        round_trip(&rich_preset());
        for preset in Preset::builtins() {
            round_trip(&PresetFile::from_core(&preset));
        }
    }

    /// The round-trip that actually matters: not "the same struct came back"
    /// but "the same ENGINE BEHAVIOR came back". Entries, chords and their
    /// guards are compared after conversion to the core model.
    #[test]
    fn preset_semantics_survive_the_json_hop() {
        let mut original = Preset::builtin_empty();
        original.name = "semantics".into();
        original.entries = vec![
            (Key::S, Binding::Button(ksx_core::XButton::A)),
            (Key::Enter, Binding::Button(ksx_core::XButton::A)),
            (Key::I, Binding::Dpad(DpadDirection::Up)),
            (
                Key::Left,
                Binding::Axis {
                    axis: Axis::X,
                    value: AXIS_MIN,
                },
            ),
            (
                Key::None,
                Binding::Axis {
                    axis: Axis::X,
                    value: -16_384,
                },
            ),
        ];
        original.chords = vec![
            Chord {
                key: Key::A,
                binding: Binding::Trigger(ksx_core::Trigger::Right),
                when: vec![Key::B, Key::C],
                unless: vec![Key::LeftShift],
            },
            Chord::consuming(Key::Left, vec![Key::Right]),
        ];
        let file = PresetFile::from_core(&original);
        let json = to_json(&file, JsonStyle::Pretty).unwrap();
        let back: Loaded<PresetFile> = parse_lenient(&p(), &json).unwrap();
        let core = back.value.to_core().unwrap();
        // Compared as SETS: `from_core` groups by function name, so entry and
        // chord ORDER is a property of the BTreeMap, not of the JSON hop.
        fn sorted<T: fmt::Debug>(items: &[T]) -> Vec<String> {
            let mut v: Vec<String> = items.iter().map(|item| format!("{item:?}")).collect();
            v.sort();
            v
        }
        assert_eq!(sorted(&core.entries), sorted(&original.entries), "{json}");
        assert_eq!(sorted(&core.chords), sorted(&original.chords), "{json}");
    }

    /// Every `BindingEntry` variant must come back as the SAME variant — an
    /// untagged enum that silently re-buckets `["A"]` into `Many` would still
    /// compare equal at the core level while corrupting the file's shape.
    #[test]
    fn every_binding_variant_keeps_its_shape_through_json() {
        let file = preset_with_nested_group();
        let json = to_json(&file, JsonStyle::Pretty).unwrap();
        let back: Loaded<PresetFile> = parse_lenient(&p(), &json).unwrap();
        assert_eq!(back.value.bindings, file.bindings, "{json}");
        assert!(matches!(
            back.value.bindings["B"],
            BindingEntry::Keys(ref keys) if keys.len() == 3
        ));
        assert!(matches!(
            back.value.bindings["rt"],
            BindingEntry::Guarded(_)
        ));
        assert!(matches!(back.value.bindings["lb"], BindingEntry::Many(_)));
        assert!(matches!(
            back.value.bindings["dpad"],
            BindingEntry::Group(_)
        ));
    }

    /// Macros needed no interop code at all — this test exists to prove the
    /// "same serde types" claim on the newest shape in the file, steps, timing
    /// flags and both policy enums included.
    #[test]
    fn macros_survive_json_untouched() {
        let file = rich_preset();
        let json = to_json(&file, JsonStyle::Pretty).unwrap();
        assert!(json.contains("\"hadouken\""), "{json}");
        assert!(json.contains("\"allow_short\": true"), "{json}");
        assert!(json.contains("\"frames\": 3"), "{json}");
        assert!(json.contains("\"on_release\": \"abort\""), "{json}");
        assert!(json.contains("\"retrigger\": \"restart\""), "{json}");
        assert!(json.contains("\"interrupt\": \"opposing\""), "{json}");
        let back: Loaded<PresetFile> = parse_lenient(&p(), &json).unwrap();
        assert_eq!(back.value.macros, rich_macros(), "{json}");
        assert_eq!(
            back.value.bindings["macro.hadouken"],
            BindingEntry::Key("P".into())
        );
    }

    /// Personas and SOCD ride the same `with = "..."` modules in both formats.
    #[test]
    fn personas_and_socd_survive_json() {
        let json = to_json(&rich_config(), JsonStyle::Compact).unwrap();
        assert!(json.contains("\"persona\":\"playstation\""), "{json}");
        assert!(json.contains("\"socd\":\"neutral\""), "{json}");
        let back: Loaded<ConfigFile> = parse_lenient(&p(), &json).unwrap();
        assert_eq!(back.value.slots[1].persona, Persona::PlayStation);
        assert_eq!(back.value.slots[1].socd, Socd::Neutral);
        // ...and the default is still omitted, so slot 1 stays clean.
        assert!(!json.contains("xbox360"), "{json}");
    }

    // ---- the envelope ------------------------------------------------------

    #[test]
    fn a_bundle_round_trips_with_every_part() {
        let bundle = Bundle {
            config: Some(rich_config()),
            games: Some(rich_games()),
            presets: Some(vec![rich_preset()]),
            ..Bundle::default()
        };
        assert_eq!(bundle.parts(), Part::ALL.to_vec());
        let json = bundle.to_json(JsonStyle::Pretty).unwrap();
        let back = parse_document(&p(), &json, None).unwrap();
        assert!(back.warnings.is_empty(), "{:?}", back.warnings);
        assert_eq!(back.value, bundle);
    }

    #[test]
    fn a_partial_bundle_omits_the_parts_it_does_not_carry() {
        let bundle = Bundle {
            games: Some(rich_games()),
            ..Bundle::default()
        };
        let json = bundle.to_json(JsonStyle::Compact).unwrap();
        assert!(!json.contains("\"config\""), "{json}");
        assert!(!json.contains("\"presets\""), "{json}");
        assert_eq!(bundle.parts(), vec![Part::Games]);
        assert_eq!(parse_document(&p(), &json, None).unwrap().value, bundle);
    }

    #[test]
    fn narrow_keeps_only_what_was_asked_for() {
        let mut bundle = Bundle {
            config: Some(rich_config()),
            games: Some(rich_games()),
            presets: Some(vec![rich_preset()]),
            ..Bundle::default()
        };
        bundle.narrow(&[Part::Presets]);
        assert_eq!(bundle.parts(), vec![Part::Presets]);
        assert!(bundle.config.is_none() && bundle.games.is_none());
    }

    #[test]
    fn a_bare_document_needs_to_be_told_what_it_is() {
        let json = to_json(&rich_preset(), JsonStyle::Pretty).unwrap();
        assert!(matches!(
            parse_document(&p(), &json, None),
            Err(ConfigError::UntaggedJson { .. })
        ));
        let loaded = parse_document(&p(), &json, Some(Part::Presets)).unwrap();
        assert_eq!(loaded.value.presets, Some(vec![rich_preset()]));
    }

    #[test]
    fn a_bare_preset_list_is_accepted() {
        let presets = vec![
            rich_preset(),
            PresetFile::from_core(&Preset::builtin_empty()),
        ];
        let json = to_json(&presets, JsonStyle::Pretty).unwrap();
        let loaded = parse_document(&p(), &json, Some(Part::Presets)).unwrap();
        assert_eq!(loaded.value.presets, Some(presets));
    }

    #[test]
    fn a_bare_config_carries_its_schema_version_into_the_envelope() {
        let json = to_json(&rich_config(), JsonStyle::Pretty).unwrap();
        let loaded = parse_document(&p(), &json, Some(Part::Config)).unwrap();
        assert_eq!(loaded.value.schema_version, SCHEMA_VERSION);
        assert_eq!(loaded.value.config, Some(rich_config()));
    }

    #[test]
    fn an_envelope_from_the_future_is_refused() {
        let json = format!(
            "{{\"ksx_interop\":{},\"schema_version\":1}}",
            INTEROP_VERSION + 1
        );
        assert!(matches!(
            parse_document(&p(), &json, None),
            Err(ConfigError::UnsupportedInteropVersion { .. })
        ));
    }

    #[test]
    fn unknown_keys_warn_instead_of_failing() {
        let json = r#"{"ksx_interop":1,"schema_version":1,"future_part":42,
                       "config":{"schema_version":1,"settings":{"frobnicate":3}}}"#;
        let loaded = parse_document(&p(), json, None).unwrap();
        assert!(loaded.value.config.is_some());
        let paths: Vec<String> = loaded
            .warnings
            .iter()
            .map(|w| match &w.kind {
                WarningKind::UnknownKey { path } => path.clone(),
                other => panic!("unexpected {other:?}"),
            })
            .collect();
        assert!(paths.contains(&"future_part".to_owned()), "{paths:?}");
        // serde_ignored spells the Option hop as `?`; what matters is that the
        // path names the field, deep inside the envelope.
        assert!(
            paths.iter().any(|p| p.ends_with("settings.frobnicate")),
            "{paths:?}"
        );
    }

    #[test]
    fn malformed_json_is_a_parse_error_naming_the_file() {
        let err = parse_document(&p(), "{not json", None).unwrap_err();
        assert!(matches!(err, ConfigError::Parse { .. }), "{err}");
        assert!(err.to_string().contains("<test>"), "{err}");
    }

    #[test]
    fn the_json_schema_gate_matches_the_toml_one() {
        assert!(json_schema_gate(&p(), r#"{"schema_version":1}"#).is_ok());
        assert!(matches!(
            json_schema_gate(&p(), r#"{"settings":{}}"#),
            Err(ConfigError::MissingSchemaVersion { .. })
        ));
        assert!(matches!(
            json_schema_gate(&p(), r#"{"schema_version":99}"#),
            Err(ConfigError::UnsupportedSchemaVersion { found: 99, .. })
        ));
    }

    #[test]
    fn formats_are_recognized_by_extension() {
        assert_eq!(Format::of(Path::new("a/config.TOML")), Some(Format::Toml));
        assert_eq!(Format::of(Path::new("a/config.Json")), Some(Format::Json));
        assert_eq!(Format::of(Path::new("a/config.yaml")), None);
        assert_eq!(Format::of(Path::new("config")), None);
        assert_eq!(Format::Json.extension(), "json");
    }

    #[test]
    fn part_names_round_trip() {
        for part in Part::ALL {
            assert_eq!(Part::parse(part.as_str()), Some(part));
        }
        assert_eq!(Part::parse("PRESET"), Some(Part::Presets));
        assert_eq!(Part::parse("nope"), None);
    }
}
