// Generated by studio-ui/tokens/build-tokens.mjs — DO NOT EDIT.
// Source of truth: studio-ui/tokens/; regenerate: cd studio-ui && node build.mjs
// CI pins this file to a fresh build alongside crates/ksx-studio/assets
// (ci.yml "Studio assets reproduce from registry dependencies").
//
// lib.rs declares this module `#[rustfmt::skip]` (an INNER #![rustfmt::skip]
// here would be cleaner but custom inner attributes are unstable, rust
// #54726); the emitted code is kept rustfmt-clean anyway, so the byte-diff
// gate and `cargo fmt --check` cannot wedge against each other.

/// Inline `<style nonce>` CSS applied before the stylesheet arrives (the
/// anti-flash trick): the body first-paints on the studio ground instead of
/// flashing white. Derived from the `--bg`/`--text` tokens in
/// `studio-ui/tokens/`, both schemes — the same source `tokens.gen.css` is
/// compiled from, so the copy CANNOT drift; `tests/contrast.rs` cross-pins
/// it anyway (a wrong anti-flash color looks exactly like the flash it
/// exists to prevent, so it gets a loud gate rather than trust).
pub(crate) const PERSONALITY_CSS: &str =
    "body{background:#120c1c;color:#f0ebe0;margin:0}@media (prefers-color-scheme:light){body{background:#f6f3ee;color:#1c1428}}";
